apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  labels:
    {{- include "ontoserverpgdb.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage }}