apiVersion: v1
kind: Service
metadata:
  labels:
    au.csiro.ontoserver: db
  name: db
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    au.csiro.ontoserver: db