apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "ontoserver.labels" . | nindent 4 }}
  name: onto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi