apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "ontoserver.labels" . | nindent 4 }}
  name: {{ include "ontoserver.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ontoserver.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ontoserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ontoserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - env:
            - name: JAVA_OPTS
              value: -Xmx8G
            - name: ONTOSERVER_INSECURE
              value: "true"
            - name: spring.datasource.url
              value: jdbc:postgresql://db/postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: {{ .Chart.Name }}
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /var/onto
              name: onto
            - mountPath: /tmp
              name: ontoserver-claim1
            - mountPath: /var/log
              name: ontoserver-claim2
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      volumes:
        - name: onto
          persistentVolumeClaim:
            claimName: onto
        - name: ontoserver-claim1
          persistentVolumeClaim:
            claimName: ontoserver-claim1
        - name: ontoserver-claim2
          persistentVolumeClaim:
            claimName: ontoserver-claim2
